# Generated by Django 4.2.4 on 2023-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_id_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('delivery_personel', 'Delivery Personel'), ('manager', 'Manager'), ('regional_manager', 'Regional Manager'), ('president', 'President')], default='user', max_length=200),
        ),
    ]
