# Generated by Django 4.2.4 on 2023-08-03 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('GAA', 'Greater Accra'), ('ASH', 'Ashanti'), ('WES', 'Western'), ('EAS', 'Eastern'), ('CEN', 'Central'), ('VOL', 'Volta'), ('NOR', 'Northern'), ('UPE', 'Upper East'), ('UPW', 'Upper West'), ('BON', 'Bono'), ('BNE', 'Bono East'), ('AHA', 'Ahafo'), ('SAV', 'Savannah'), ('NER', 'North East')], max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
