# Generated by Django 4.2.4 on 2023-08-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='id',
            new_name='custom_id',
        ),
    ]
