# Generated by Django 4.2.4 on 2023-08-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_rename_id_store_custom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='custom_id',
            new_name='store_id',
        ),
    ]
